---
title: "WKCLIMAD Chord Diagram"
author: "K Holsman"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
# based on code avail at
# https://nefsc.github.io/READ-SSB-DePiper_Summer_Flounder_Conceptual_Models/sfconsmod_final_2col.html

knitr::opts_chunk$set(echo = FALSE)
# PKG <- c(#"foreign","foodweb","sna",
#          "DiagrammeR","circlize","RColorBrewer","QPress",
#          "chorddiag", "kableExtra", "googledrive", "readxl",
#          "DT")
# for (p in PKG) {
#   if(!require(p,character.only = TRUE)) {
#     install.packages(p)
#     require(p,character.only = TRUE)}
# }
#install QPress
#install.packages(c("tcltk2", "XML", "devtools"))
#devtools::install_github("SWotherspoon/QPress", build_vignettes = TRUE)
#install chorddiag
#devtools::install_github("mattflor/chorddiag")
#install googlesheets4
#devtools::install_github("tidyverse/googlesheets4")
#install bsselectR
#devtools::install_github("walkerke/bsselectR")
```


```{r sfmod setup, message=FALSE, warning=FALSE}
  suppressMessages(source("R/make.R"))
 
     modlist <- models[1:3]
    # NewChord(modlist)
     
      # create legend for plotting
  cat <- data.frame(ID = unique(c(links_all$source,links_all$destination)))%>%
    left_join(tbl, by=c("ID"="ID"))
  
  by_category <- cat%>%group_by(plotID,Category)%>%
    summarize(freq=length(plotID))%>%
    arrange(Category, plotID)%>%
    mutate(plotID = factor(plotID,plotID))%>%rename(lab = Category)
  cc            <- viridis_pal(alpha = 1, begin = 0, end = 1, direction = 1, option = "D")
  by_category$cols <- cc(length(unique(by_category$lab)))[as.numeric(as.factor(by_category$lab))]
  legend        <- by_category%>% select(lab,cols)%>%distinct()

```

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}

.column-left{
  float: left;
  width: 30%;
  text-align: left;
  font-size: 150%;
}
.column-right{
  float: right;
  width: 70%;
  text-align: center;
}

</style>

<div class="column-left">
### Categories
```{r selectquestion}
# 
# #from https://walkerke.github.io/2016/12/rmd-dropdowns/
# library(bsselectR)

plot(NULL ,xaxt='n',yaxt='n',bty='n',ylab='',xlab='', xlim=0:1, ylim=0:1)
legend("topleft", #x=-1.1,y = 1.09,
       
       legend = legend$lab,
             lty= 1, lwd=15,
             col =legend$cols, ncol=1, cex = 1.5, bg = NULL, box.col=NULL, bty = "n")

quotes <- c("How does utilizing recreational data sources at scales that may be inappropriate for the data source (e.g., MRIP data at the state/wave/mode level) affect management variability, uncertainty, and fishery performance? Evaluate the impact of that variability and uncertainty and its use in the current conservation equivalency process on recreational fishery outcomes.", 
            "What are the mechanisms driving summer flounder distribution shift and/or population range expansion? What are the biological, management, and socioeconomic implications of these changes? Identify potential management and science strategies to help account for the impacts of these changes.", 
            "Evaluate the biological and economic benefits of minimizing discards and converting discards into landings in the recreational sector. Identify management strategies to effectively realize these benefits.")

names(quotes) <- c("1", "2", "3")

bsselect(quotes, type = "text")


```

</div>

<div class="column-right">
### Interactions
```{r sfint-full}
#New_Figure(colnames(FLUKE_edges2))
suppressMessages(NewChord(modlist))
```

</div>